name: ci-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - uses: actions/checkout@v2

      - name: Test
        run: make test

      - name: Run golangci-lint on cart-service
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: cart-service

      - name: Run golangci-lint on common
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: common

      - name: Run golangci-lint on delivery-service
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: delivery-service

      - name: Run golangci-lint on inventory-service
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: inventory-service

      - name: Run golangci-lint on order-service
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: order-service

      - name: Run golangci-lint on payment-service
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: payment-service

      - name: Run golangci-lint on product-service
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: product-service

      - name: Run golangci-lint on proto
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: proto

      - name: Run golangci-lint on ui_client
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ui_client

      - name: Run golangci-lint on user-service
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: user-service
